using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Security.Cryptography;
using System.Drawing;
using System.IO;
using System.Text;
using System.Windows.Forms;

namespace Emdee_Five
{
    class Program : Form
    {
        // Items generated by form designer
        private ProgressBar pbProgress;
        private Label lblProgress;
        private Label lblMD5;
        private TextBox tbMD5;
        private OpenFileDialog ofdSelectFile;
        private Button btnSelectFile;
        private StatusStrip StatusBar;
        private ToolStripStatusLabel lblStatus;
        // Background worker to update the progress bar
        private BackgroundWorker bwProgress = new BackgroundWorker();
    
        public Program()
        {
            // InitializeComponent routine generated by form designer
            InitializeComponent();
            // Setup the background worker
            bwProgress.WorkerReportsProgress = true;
            bwProgress.DoWork += new DoWorkEventHandler(bwDoWork);
            bwProgress.ProgressChanged += new ProgressChangedEventHandler(bwDoProgress);
            bwProgress.RunWorkerCompleted += new RunWorkerCompletedEventHandler(bwWorkDone);
        }

        // The workhorse, performs the MD5 hashing after the file is selected
        private void bwDoWork(Object o, DoWorkEventArgs e)
        {
            // Get the filename
            string sFileName = (string)e.Argument;
            // Open the file in a file stream
            FileStream fStream = new FileStream(sFileName, FileMode.Open);
            // Create a new MD5 service and a cryptostream to the open file using it
            MD5CryptoServiceProvider MD5Service = new MD5CryptoServiceProvider();
            CryptoStream cStream = new CryptoStream(fStream, MD5Service, CryptoStreamMode.Read);
            // 10 Megabyte buffer
            Byte[] bBuffer = new Byte[10240];
            // Get the file size
            long lFileSize = fStream.Length;
            // Used to track the progress through the file
            long iBytesRead = -1, iTotalRead = 0;
            // do while we are actually reading something
            do
            {
                // Read the stream, get the number of bytes read
                iBytesRead = cStream.Read(bBuffer, 0, bBuffer.Length);
                // Increment our total bytes counter
                iTotalRead += iBytesRead;
                // Find out the percentage of the file that we've read
                float p = (float)(((ulong)iTotalRead * 100.0f) / lFileSize);
                // Update the progress
                bwProgress.ReportProgress((int)p);
            } while (iBytesRead != 0);
            // Close the streams
            cStream.Close();
            fStream.Close();
            // Use the string builder to build up a string from the Byte array containing our hash
            StringBuilder sb = new StringBuilder();
            for(int i = 0; i < MD5Service.Hash.Length; i++)
            {
                sb.Append(MD5Service.Hash[i].ToString("x2"));
            }
            // Return the hash
            e.Result = sb.ToString();
        }

        // Update the progress bar, as well as the progress status bar
        private void bwDoProgress(Object o, ProgressChangedEventArgs e)
        {           
            pbProgress.Value = e.ProgressPercentage;
            lblStatus.Text = "..." + e.ProgressPercentage + "%";
        }

        // When the work is complete, display the completed hash in the text box
        private void bwWorkDone(Object o, RunWorkerCompletedEventArgs e)
        {
            lblStatus.Text = "Completed!";
            tbMD5.Text = (string)e.Result;
        }
        
#if DEBUG
        [STAThread]
#endif
        static void Main()
        {
            using (Program p = new Program())
            {
                p.Show();
                while (p.Created)
                {
                    Application.DoEvents();
                }
            }
        }

        private void InitializeComponent()
        {
            this.btnSelectFile = new System.Windows.Forms.Button();
            this.pbProgress = new System.Windows.Forms.ProgressBar();
            this.lblProgress = new System.Windows.Forms.Label();
            this.lblMD5 = new System.Windows.Forms.Label();
            this.tbMD5 = new System.Windows.Forms.TextBox();
            this.ofdSelectFile = new System.Windows.Forms.OpenFileDialog();
            this.StatusBar = new System.Windows.Forms.StatusStrip();
            this.lblStatus = new System.Windows.Forms.ToolStripStatusLabel();
            this.StatusBar.SuspendLayout();
            this.SuspendLayout();
            // 
            // btnSelectFile
            // 
            this.btnSelectFile.Location = new System.Drawing.Point(15, 67);
            this.btnSelectFile.Name = "btnSelectFile";
            this.btnSelectFile.Size = new System.Drawing.Size(75, 23);
            this.btnSelectFile.TabIndex = 0;
            this.btnSelectFile.Text = "Select File";
            this.btnSelectFile.UseVisualStyleBackColor = true;
            this.btnSelectFile.Click += new System.EventHandler(this.btnSelectFile_Click);
            // 
            // pbProgress
            // 
            this.pbProgress.Location = new System.Drawing.Point(69, 12);
            this.pbProgress.Name = "pbProgress";
            this.pbProgress.Size = new System.Drawing.Size(203, 23);
            this.pbProgress.TabIndex = 1;
            // 
            // lblProgress
            // 
            this.lblProgress.AutoSize = true;
            this.lblProgress.Location = new System.Drawing.Point(12, 22);
            this.lblProgress.Name = "lblProgress";
            this.lblProgress.Size = new System.Drawing.Size(51, 13);
            this.lblProgress.TabIndex = 2;
            this.lblProgress.Text = "Progress:";
            // 
            // lblMD5
            // 
            this.lblMD5.AutoSize = true;
            this.lblMD5.Location = new System.Drawing.Point(12, 48);
            this.lblMD5.Name = "lblMD5";
            this.lblMD5.Size = new System.Drawing.Size(33, 13);
            this.lblMD5.TabIndex = 3;
            this.lblMD5.Text = "MD5:";
            // 
            // tbMD5
            // 
            this.tbMD5.BackColor = System.Drawing.Color.White;
            this.tbMD5.Location = new System.Drawing.Point(51, 41);
            this.tbMD5.Name = "tbMD5";
            this.tbMD5.ReadOnly = true;
            this.tbMD5.Size = new System.Drawing.Size(221, 20);
            this.tbMD5.TabIndex = 4;
            // 
            // StatusBar
            // 
            this.StatusBar.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.lblStatus});
            this.StatusBar.Location = new System.Drawing.Point(0, 96);
            this.StatusBar.Name = "StatusBar";
            this.StatusBar.Size = new System.Drawing.Size(284, 22);
            this.StatusBar.TabIndex = 5;
            this.StatusBar.Text = "statusStrip1";
            // 
            // lblStatus
            // 
            this.lblStatus.Name = "lblStatus";
            this.lblStatus.Size = new System.Drawing.Size(171, 17);
            this.lblStatus.Text = "Click \"Select File\" to hash a file.";
            // 
            // Program
            // 
            this.ClientSize = new System.Drawing.Size(284, 118);
            this.Controls.Add(this.StatusBar);
            this.Controls.Add(this.tbMD5);
            this.Controls.Add(this.lblMD5);
            this.Controls.Add(this.lblProgress);
            this.Controls.Add(this.pbProgress);
            this.Controls.Add(this.btnSelectFile);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.Name = "Program";
            this.Text = "Emdee Five";
            this.StatusBar.ResumeLayout(false);
            this.StatusBar.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        private void btnSelectFile_Click(object sender, EventArgs e)
        {
            tbMD5.Text = "";
            pbProgress.Value = 0;
            ofdSelectFile.ShowDialog();
            bwProgress.RunWorkerAsync(ofdSelectFile.FileName);
        }
    }
}
